# Site settings
baseurl: "/ore-ero"
url: "https://canada-ca.github.io/ore-ero"
github_username: canada-ca
github_repository: ore-ero
prbot_url: "https://canada-pr-bot.herokuapp.com/"

wet_cdts_hosturl: "https://www.canada.ca/etc/designs/canada/cdts/gcweb"
wet_cdts_version: "v4_0_30"

active_emergency: true
active_emergency_name: "COVID-19"
high_value_tag: "BCP-PCA"

excludeTag: "Exclude-Exclure"

# Build settings
markdown: kramdown
include: ["_pages", "_json"]
