---

id: software

formGroups:
  - preset: selectSoftware
  - preset: description
  - preset: category
  - preset: tags
  - preset: homepageURL
    param: {type: url}
  - preset: licences
    param: {more: true}
  - preset: uses
    param: {more: true}
  - preset: empty
  - preset: empty
