---

id: admin

formGroups:
  - preset: orgLevel
  - widget: select
    title: ProvinceCode
    required: false
<<<<<<< HEAD
    options: [ ab, bc, mb, nb, nl, nt, ns, nu, "on", pe, qc, sk, yt ] # on is a yaml/liquid/jekyll keyword and thus must be escaped
=======
    options: [ab, bc, mb, nb, nl, nt, ns, nu, "on", pe, qc, sk, yt] # on is a yaml/liquid/jekyll keyword and thus must be escaped
>>>>>>> a820a6418c4faf5e4a3c70810d8f09a3be49ad90
  - widget: string-i18n
    title: Name
    rule: alphanum-space
